"""empty message

<<<<<<<< HEAD:migrations/versions/a4e9262738ed_.py
Revision ID: a4e9262738ed
Revises: 
Create Date: 2023-03-23 23:53:05.481030
========
Revision ID: 280d960090e5
Revises: 
Create Date: 2023-03-23 22:16:57.927150
>>>>>>>> 407f5df6f668eae72a9252f9dc769db7ae4a80d4:migrations/versions/280d960090e5_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/a4e9262738ed_.py
revision = 'a4e9262738ed'
========
revision = '280d960090e5'
>>>>>>>> 407f5df6f668eae72a9252f9dc769db7ae4a80d4:migrations/versions/280d960090e5_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicios', sa.String(length=255), nullable=True),
    sa.Column('tipo_animal', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mayores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicios', sa.String(length=255), nullable=True),
    sa.Column('formacion', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicios', sa.String(length=255), nullable=True),
    sa.Column('edades', sa.String(length=120), nullable=True),
    sa.Column('cualificacion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('es_cuidador', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peques_id', sa.Integer(), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=True),
    sa.Column('mayores_id', sa.Integer(), nullable=True),
    sa.Column('categorias_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categorias_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascota.id'], ),
    sa.ForeignKeyConstraint(['mayores_id'], ['mayores.id'], ),
    sa.ForeignKeyConstraint(['peques_id'], ['peques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('experiencia', sa.String(length=255), nullable=True),
    sa.Column('tarifa', sa.Integer(), nullable=True),
    sa.Column('plus_tarifa', sa.Integer(), nullable=True),
    sa.Column('puntuacion_global', sa.Integer(), nullable=True),
    sa.Column('cantidad_votos', sa.Integer(), nullable=True),
    sa.Column('numero_telefono', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(length=120), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('educacion', sa.String(length=255), nullable=True),
    sa.Column('tipo_servicios', sa.String(length=255), nullable=True),
    sa.Column('redes_sociales', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valoracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=120), nullable=True),
    sa.Column('codigo_postal', sa.String(length=120), nullable=True),
<<<<<<<< HEAD:migrations/versions/a4e9262738ed_.py
    sa.Column('ciudad', sa.String(length=120), nullable=True),
========
    sa.Column('ciudad', sa.String(length=255), nullable=True),
    sa.Column('provincia', sa.String(length=120), nullable=True),
>>>>>>>> 407f5df6f668eae72a9252f9dc769db7ae4a80d4:migrations/versions/280d960090e5_.py
    sa.Column('direccion_user_info', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['direccion_user_info'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion_user_info')
    )
    op.create_table('foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('foto_imagen', sa.String(length=255), nullable=True),
    sa.Column('foto_user_info', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foto_user_info'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('foto_user_info')
    )
    op.create_table('resenas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opinion', sa.String(length=120), nullable=True),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('puntuacion', sa.String(length=120), nullable=True),
    sa.Column('resenas_valoracion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resenas_valoracion'], ['valoracion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resenas')
    op.drop_table('foto')
    op.drop_table('direccion')
    op.drop_table('valoracion')
    op.drop_table('user_info')
    op.drop_table('categorias')
    op.drop_table('users')
    op.drop_table('user')
    op.drop_table('peques')
    op.drop_table('mayores')
    op.drop_table('mascota')
    # ### end Alembic commands ###
