"""empty message

Revision ID: a8fe8e854e79
Revises: 
Create Date: 2023-03-21 19:21:51.199919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fe8e854e79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_animal', sa.String(length=120), nullable=False),
    sa.Column('servicios', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mayores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicios', sa.String(length=120), nullable=False),
    sa.Column('formacion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_adicional', sa.String(length=120), nullable=False),
    sa.Column('edades', sa.String(length=120), nullable=False),
    sa.Column('cualificacion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('es_profesional', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peques_id', sa.Integer(), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=True),
    sa.Column('mayores_id', sa.Integer(), nullable=True),
    sa.Column('categorias_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorias_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascota.id'], ),
    sa.ForeignKeyConstraint(['mayores_id'], ['mayores.id'], ),
    sa.ForeignKeyConstraint(['peques_id'], ['peques.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categorias_user')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('experiencia', sa.String(), nullable=False),
    sa.Column('tarifa', sa.Integer(), nullable=False),
    sa.Column('plus_tarifa', sa.Integer(), nullable=False),
    sa.Column('puntuacion_global', sa.Integer(), nullable=False),
    sa.Column('cantidad_votos', sa.Integer(), nullable=False),
    sa.Column('numero_telefono', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=120), nullable=False),
    sa.Column('direccion_perfil', sa.String(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('educacion', sa.String(), nullable=False),
    sa.Column('tipo_servicios', sa.String(), nullable=False),
    sa.Column('redes_sociales', sa.String(length=120), nullable=False),
    sa.Column('user_info_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_info_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valoracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=True),
    sa.Column('user_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=120), nullable=False),
    sa.Column('codigo_postal', sa.String(length=120), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=False),
    sa.Column('direccion_user_info', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['direccion_user_info'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion_user_info')
    )
    op.create_table('foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('foto_imagen', sa.Integer(), nullable=False),
    sa.Column('foto_user_info', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foto_user_info'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('foto_user_info')
    )
    op.create_table('resenas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opinion', sa.String(length=120), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('puntuacion', sa.String(length=120), nullable=False),
    sa.Column('resenas_valoracion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resenas_valoracion'], ['valoracion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resenas')
    op.drop_table('foto')
    op.drop_table('direccion')
    op.drop_table('valoracion')
    op.drop_table('user_info')
    op.drop_table('categorias')
    op.drop_table('user')
    op.drop_table('peques')
    op.drop_table('mayores')
    op.drop_table('mascota')
    # ### end Alembic commands ###
