"""empty message

Revision ID: d03ef7e647ca
Revises: 4627878787d4
Create Date: 2023-03-22 02:05:18.980443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03ef7e647ca'
down_revision = '4627878787d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_cuidador', sa.Boolean(), nullable=True))
        batch_op.drop_column('es_profesional')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_profesional', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('es_cuidador')

    # ### end Alembic commands ###
