"""empty message

Revision ID: e0898fdfed14
Revises: d3da4af877cd
Create Date: 2023-03-23 15:40:15.856446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0898fdfed14'
down_revision = 'd3da4af877cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direccion', schema=None) as batch_op:
        batch_op.alter_column('ciudad',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('direccion_user_info',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direccion', schema=None) as batch_op:
        batch_op.alter_column('direccion_user_info',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ciudad',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
